#Aprendido em https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html

all: pingpong-dispatcher.c queue.c
	gcc -g -Wall -o pingpong-dispatcher pingpong-dispatcher.c pingpong.c queue.c
clean:
	$(RM) p02
