#Aprendido em https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html


pingpong-tasks1: pingpong-tasks1.c
	gcc -g -Wall -o pingpong-tasks1 pingpong-tasks1.c pingpong.c
pingpong-tasks2: pingpong-tasks2.c
	gcc -g -Wall -o pingpong-tasks2 pingpong-tasks2.c pingpong.c
pingpong-tasks3: pingpong-tasks3.c
	gcc -g -Wall -o pingpong-tasks3 pingpong-tasks3.c pingpong.c
clean:
	$(RM) p02
