#Aprendido em https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html

all: pingpong-scheduler.c
	gcc -g -Wall -o pingpong-scheduler pingpong-scheduler.c pingpong.c queue.c
clean:
	$(RM) p02
