#Aprendido em https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html

all: pingpong-preempcao.c
	gcc -g -Wall -o pingpong-preempcao pingpong-preempcao.c pingpong.c queue.c timer.c
clean:
	$(RM) p02
